package:
  name: keras
  version: "2.0.0"

source:
  git_rev: 2.0.0
  git_url: https://github.com/fchollet/keras.git

requirements:
  build:
    - python
    - setuptools
    - tensorflow
    - pyyaml
    - six
    - h5py
    - pydot-ng
    - pytest
    - pytest-pep8
    - pytest-xdist
    - protobuf
    - theano
  run:
    - python
    - tensorflow
    - pyyaml
    - six
    - h5py
    - pydot-ng
    - pytest
    - pytest-pep8
    - pytest-xdist
    - protobuf
    - theano
test:
  imports:
    - keras
    - theano
about:
  home: https://github.com/fchollet/keras
  license: MIT
  license_file: LICENSE
